site_name: MLOpsAditya
site_description: Multi-branch documentation viewer
site_author: Aditya Pratap Singh

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

nav:
  - Home: index.md
  - Branch Docs:
      - Assignment 1: branches/assg_1.md
      - Assignment 2: branches/assg_2.md
      - Assignment 3: branches/assg_3.md
      - Assignment 4: branches/assg_4.md
      - Assignment 5: branches/assg_5.md
      - Worksheet 1: branches/worksheet1.md



markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true