site_name: My Project Docs
site_description: Multi-branch documentation viewer
site_author: Aditya Pratap Singh

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode

nav:
  - Home: index.md
  - Branch Docs:
      - Branch 1: branches/branch1.md
      - Branch 2: branches/branch2.md
      - Branch 3: branches/branch3.md
      - Branch 4: branches/branch4.md
      - Branch 5: branches/branch5.md
      - Branch 6: branches/branch6.md



markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true